name: klontong
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  dio: ^5.0.0
  equatable: ^2.0.3
  provider: ^6.0.3
  shared_preferences: ^2.0.11
  intl: ^0.19.0
  firebase_core: ^2.12.0
  firebase_crashlytics: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.7
  mockito: ^5.4.4

flutter:
  uses-material-design: true
